// <auto-generated />
using System;
using AlterdataVotador.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AlterdataVotador.Migrations
{
    [DbContext(typeof(AlterdataVotadorContext))]
    partial class AlterdataVotadorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AlterdataVotador.Models.MelhoriasVotar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataVotacao_Votar");

                    b.Property<string>("DetalheDaMemoria_Votar");

                    b.Property<string>("MelhoriaArea");

                    b.Property<int?>("ModuloId");

                    b.Property<string>("NomeModulo");

                    b.Property<string>("QuantVotos");

                    b.Property<bool>("TrueFalse_Votar");

                    b.Property<int?>("VotarHomeId");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("VotarHomeId");

                    b.ToTable("MelhoriasVotar");
                });

            modelBuilder.Entity("AlterdataVotador.Models.ModulosVotar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LinhaDoModulo");

                    b.Property<string>("NameModulos");

                    b.HasKey("Id");

                    b.ToTable("ModulosVotar");
                });

            modelBuilder.Entity("AlterdataVotador.Models.UsuariosAcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DatNass");

                    b.Property<string>("Email");

                    b.Property<int>("ModulosId");

                    b.Property<string>("NomeUsuario");

                    b.Property<string>("PassWord");

                    b.Property<string>("TimeZoneUSuario");

                    b.HasKey("Id");

                    b.HasIndex("ModulosId");

                    b.ToTable("UsuariosAcess");
                });

            modelBuilder.Entity("AlterdataVotador.Models.UsuarioVota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Id_MelhoriaVotada");

                    b.Property<string>("NomeUsuario");

                    b.Property<string>("TimeZone");

                    b.HasKey("Id");

                    b.ToTable("UsuarioVotar");
                });

            modelBuilder.Entity("AlterdataVotador.Models.VotarHome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataVotar");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("VotaHome");
                });

            modelBuilder.Entity("AlterdataVotador.Models.MelhoriasVotar", b =>
                {
                    b.HasOne("AlterdataVotador.Models.ModulosVotar", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId");

                    b.HasOne("AlterdataVotador.Models.VotarHome")
                        .WithMany("MelhoriasR")
                        .HasForeignKey("VotarHomeId");
                });

            modelBuilder.Entity("AlterdataVotador.Models.UsuariosAcess", b =>
                {
                    b.HasOne("AlterdataVotador.Models.ModulosVotar", "Modulos")
                        .WithMany()
                        .HasForeignKey("ModulosId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
